import Head from "next/head";
import HomeScreen from "../src/screen/home/Home";
export default function Home() {
  return (
    <>
      <Head>
        <title>Colors </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeScreen />
    </>
  );
}
